/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Lenovo
 */
public class transaksigaji extends javax.swing.JFrame {
public String id, nama, jenis, agama,pendidikan, nik, telp, jabatan, mulai, alamat,gapok,nominal;
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;
    /**
     * Creates new form transaksigaji
     */
    public transaksigaji() {
        initComponents();
        kosong();
        datatable();
        autotrx();
    }

    protected void kosong(){
        txtid.setText("");
        txtnama.setText("");
        cbjabatan.setSelectedItem("Masukan Jabatan");
        gajipokok.setText("");
        txtnm1.setText("");
        txtbln.setSelectedItem("Pilih Bulan");
        txtket.setSelectedItem("Pilih Keterangan");
        txtnb.setText("");
        txtbns.setText("");
        txtbonus.setText("");
        bpjs.setText("");
        hbpjs.setText("");
        pajak.setText("");
        hpajak.setText("");
        gakor.setText("");
        txttotal.setText("");
    }
    
    protected void itemTerpilih1(){
         popuppegawai4 Pp = new popuppegawai4();
         Pp.pgw3 = this;
         txtnm1.setText(nama);
         }
    
    protected void itemTerpilihGaji(){
         popupgaji Pp = new popupgaji();
         Pp.dgj = this;
         txtid.setText(id);
         txtnama.setText(nama);
         cbjabatan.setSelectedItem(jabatan);
         gajipokok.setText(gapok);
         }
    
    protected void itemTerpilihTjk(){
         popuptunjangan Pp = new popuptunjangan();
         Pp.tjk = this;
         txtnb.setText(nominal);
         }
    
protected void autotrx(){
    try {
        String sql = "SELECT idtrx FROM transaksi ORDER BY idtrx DESC LIMIT 1";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);

        int AN = 1;  // Default jika tidak ada data, mulai dari 1
        if (rs.next()) {
            String idnota = rs.getString("idtrx");
            
            // Pastikan string minimal 2 karakter
            if (idnota != null && idnota.length() >= 2) {
                String angka = idnota.substring(2); // Ambil setelah 'IN'
                AN = Integer.parseInt(angka) + 1;
            }
        }

        String Nol = "";
        if(AN < 10) {
            Nol = "000";
        } else if(AN < 100) {
            Nol = "00";
        } else if(AN < 1000) {
            Nol = "0";
        }

        idtrx.setText("IN" + Nol + AN);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Auto Number Gagal: " + e);
    }
}





    
    protected void datatable(){
    Object[] Baris ={"ID Pegawai","Nama Pegawai","Jabatan","Gaji Pokok","tunjangan","Absensi","Bonus Absensi","-Bpjs","-Pajak","Gaji Kotor","Gaji Bersih","ID Transaksi"};
       tabmode = new DefaultTableModel(null, Baris);
       String cariitem=txtcari.getText();
       
       try{
           String sql = "SELECT * FROM transaksi where id like '%"+cariitem+"%' or nama like '%"+cariitem+"' order by id asc";
           Statement stat = conn.createStatement();
           ResultSet hasil = stat.executeQuery(sql);
           while (hasil.next()){
               tabmode.addRow(new Object[]{
               hasil.getString(1),
               hasil.getString(2),
               hasil.getString(3),
               hasil.getString(4),  
               hasil.getString(5),
               hasil.getString(6),
               hasil.getString(7),
               hasil.getString(8),
               hasil.getString(9),
               hasil.getString(10),  
               hasil.getString(11),
               hasil.getString(12)
           });
           }
           tblpegawai.setModel(tabmode);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal di panggil"+e);
       }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        isi1 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbjabatan = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpegawai = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        txtnb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txttotal1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        txtnm1 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        txtbns = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        gajipokok = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        bpjs = new javax.swing.JTextField();
        hbpjs = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        gakor = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        pajak = new javax.swing.JTextField();
        hpajak = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        bhitung = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtbln = new javax.swing.JComboBox<>();
        txtket = new javax.swing.JComboBox<>();
        txtbonus = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        bsimpan2 = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        idtrx = new javax.swing.JTextField();
        txtcetak = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Hi Admin");

        jPanel4.setMaximumSize(new java.awt.Dimension(137, 143));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vector-users-icon (1).jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setPreferredSize(new java.awt.Dimension(137, 143));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel9.setText("Data Pegawai");

        jLabel16.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel16.setText("Data Gaji");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel11.setText("Data Absensi");

        jLabel22.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel22.setText("Data Tunjangan");

        jLabel26.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel26.setText("Transaksi Gaji");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Teacher_1.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/List.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Dollar Bag.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Magnetic Card.png"))); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sale Price Tag.png"))); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card Payment.png"))); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel27.setText("Data Rekening");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel25))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(73, 73, 73))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jLabel16)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26))
                .addGap(350, 350, 350)
                .addComponent(jLabel25)
                .addGap(3837, 3837, 3837))
        );

        isi1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel20.setBackground(new java.awt.Color(0, 0, 0));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("FORM TRANSAKSI GAJI");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 23, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("ID Pegawai");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 94, -1, 37));
        jPanel3.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 94, 194, 37));
        jPanel3.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 145, 234, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Nama Pegawai");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 143, -1, 37));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel13.setText("Jabatan");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 199, -1, 37));

        cbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masukan Jabatan", "KEPALA SEKOLAH", "ADMINISTRASI", "GURU - BK", "GURU - MATEMATIKA", "GURU - B INDONESIA", "GURU - B INGGRIS", "GURU - KEWARGANEGARAAN", "GURU - SOSIAL BUDAYA", "GURU - JASMANI", "GURU - DESAIN GRAFIS", "GURU - ADMINISTRASI", "GURU - KOMPUTER JARINGAN", "SATPAM", "PETUGAS KEBERSIHAN" }));
        jPanel3.add(cbjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 200, 234, 32));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel15.setText("Tunjangan");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 94, -1, 22));

        edit.setBackground(new java.awt.Color(0, 51, 0));
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel3.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 430, 100, 33));

        tblpegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblpegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpegawai);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 475, 870, 180));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 40, 40));

        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Google Web Search_1.png"))); // NOI18N
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 94, -1, 37));

        txtnb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnbActionPerformed(evt);
            }
        });
        jPanel3.add(txtnb, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 94, 196, 34));

        jLabel5.setText("Gaji Bersih");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        txttotal.setEditable(false);
        txttotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 250, 33));

        txttotal1.setBorder(null);
        jPanel3.add(txttotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 799, 172, 33));

        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Google Web Search_1.png"))); // NOI18N
        jButton10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(809, 94, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel18.setText("Absensi");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 294, -1, 22));

        txtnm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnm1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtnm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 294, 196, 34));

        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Google Web Search_1.png"))); // NOI18N
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 294, -1, -1));

        txtbns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbnsActionPerformed(evt);
            }
        });
        jPanel3.add(txtbns, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 145, 184, 31));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel19.setText("Jumlah Absensi");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 150, -1, 22));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel20.setText("Gaji Pokok");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 249, -1, 22));
        jPanel3.add(gajipokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 242, 234, 34));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel21.setText("Potongan BPJS %");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 240, 90, 22));
        jPanel3.add(bpjs, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 240, 110, 32));

        hbpjs.setEditable(false);
        jPanel3.add(hbpjs, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 240, 130, 32));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel23.setText("Gaji Kotor");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 70, 22));

        gakor.setEditable(false);
        jPanel3.add(gakor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 250, 34));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel24.setText("Potongan Pajak %");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 290, 90, 22));
        jPanel3.add(pajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 290, 110, 30));

        hpajak.setEditable(false);
        jPanel3.add(hpajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 290, 130, 30));

        jButton7.setText("GET");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 144, 54, 34));

        bhitung.setBackground(new java.awt.Color(0, 51, 0));
        bhitung.setForeground(new java.awt.Color(255, 255, 255));
        bhitung.setText("Hitung");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });
        jPanel3.add(bhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 250, 33));

        jLabel7.setText("Bulan");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 346, -1, -1));

        jLabel8.setText("Keterangan");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 401, -1, -1));

        txtbln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Bulan", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel3.add(txtbln, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 346, 236, 33));

        txtket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Keterangan", "Hadir", "Izin", "Sakit", "Alfa" }));
        jPanel3.add(txtket, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 393, 236, 29));

        txtbonus.setEditable(false);
        jPanel3.add(txtbonus, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 192, 244, 27));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel28.setText("Bonus Absensi");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 195, -1, 22));

        bsimpan2.setBackground(new java.awt.Color(0, 51, 0));
        bsimpan2.setForeground(new java.awt.Color(255, 255, 255));
        bsimpan2.setText("SIMPAN");
        bsimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpan2ActionPerformed(evt);
            }
        });
        jPanel3.add(bsimpan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 118, 33));

        hapus.setBackground(new java.awt.Color(0, 51, 0));
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel3.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 118, 33));
        jPanel3.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 670, 170, 30));

        jButton9.setText("Cari");
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 670, -1, 30));

        idtrx.setEditable(false);
        jPanel3.add(idtrx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 150, 30));
        jPanel3.add(txtcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 32, 140, 40));

        jPanel20.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 960, 730));

        javax.swing.GroupLayout isi1Layout = new javax.swing.GroupLayout(isi1);
        isi1.setLayout(isi1Layout);
        isi1Layout.setHorizontalGroup(
            isi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isi1Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 561, Short.MAX_VALUE))
        );
        isi1Layout.setVerticalGroup(
            isi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isi1Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3351, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(isi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(isi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jMenu1.setText("Options");

        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        String sql = "update transaksi set nama=?,jabatan=?,gapok=?,tunjangan=?,absensi=?,bonus=?,bpjs=?,pajak=?,gakor=?,gaber=?,idtrx=? where id='"+txtid.getText()+"'";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnama.getText());
            stat.setString(2, cbjabatan.getSelectedItem().toString());
            stat.setString(3, gajipokok.getText());
            stat.setString(4, txtnb.getText());
            stat.setString(5, txtbns.getText());
            stat.setString(6, txtbonus.getText());
            stat.setString(7, hbpjs.getText());
            stat.setString(8, hpajak.getText());
            stat.setString(9, gakor.getText());
            stat.setString(10, txttotal.getText());
            stat.setString(11, idtrx.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            autotrx();
            txtid.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null,"data gagal diubah"+e);
        }
        datatable();

    }//GEN-LAST:event_editActionPerformed

    private void tblpegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpegawaiMouseClicked
        int bar = tblpegawai.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
        String k = tabmode.getValueAt(bar, 10).toString();
        
        txtid.setText(a);
        txtnama.setText(b);
        cbjabatan.setSelectedItem(c);
        gajipokok.setText(d);
        txtnb.setText(e);
        txtbns.setText(f);
        txtbonus.setText(g);
        hbpjs.setText(h);
        hpajak.setText(i);
        gakor.setText(j);
        txttotal.setText(k);
    }//GEN-LAST:event_tblpegawaiMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        popupgaji Pp = new popupgaji();
        Pp.dgj = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtnbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnbActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtnbActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        popuptunjangan Pp = new popuptunjangan();
        Pp.tjk = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtnm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnm1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        popuppegawai4 Pp = new popuppegawai4();
        Pp.pgw3 = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
        double pj = Double.parseDouble(pajak.getText());
        double gj = Double.parseDouble(gajipokok.getText());
        double bp = Double.parseDouble(bpjs.getText());
        double bns = Double.parseDouble(txtbonus.getText());
        double tj = Double.parseDouble(txtnb.getText());
        
        double pjk = (pj/100)*gj;
        double bpjk = (bp/100)*gj;
        double gjk = gj+bns+tj;
        double gjb = gjk-pjk-bpjk;
        
        hpajak.setText(String.valueOf(pjk));
        hbpjs.setText(String.valueOf(bpjk));
        gakor.setText(String.valueOf(gjk));
        txttotal.setText(String.valueOf(gjb));
    }//GEN-LAST:event_bhitungActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String namas = txtnm1.getText();
String bulanStr = txtbln.getSelectedItem().toString();
String keterangan = txtket.getSelectedItem().toString();

if (namas.isEmpty() || bulanStr.isEmpty() || keterangan.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Nama, Bulan Dan Keterangan Tidak Boleh Kosong");
    return;
}

int bulan = Integer.parseInt(bulanStr);

try {
    String sql = "SELECT COUNT(*) AS total FROM dataabsen " +
                 "WHERE nama = ? AND MONTH(tanggal) = ? AND keterangan = ?";
    PreparedStatement stat = conn.prepareStatement(sql);
    stat.setString(1, namas);
    stat.setInt(2, bulan);
    stat.setString(3, keterangan);

    ResultSet rs = stat.executeQuery();
    if (rs.next()) {
        int total = rs.getInt("total");
        txtbns.setText(String.valueOf(total));
    } else {
        txtbns.setText("0");
    }
    rs.close();
    stat.close();

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Gagal Mencari Absensi");
}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bsimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpan2ActionPerformed
        // TODO add your handling code here:
         String sql = "insert into transaksi values (?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtid.getText());
            stat.setString(2, txtnama.getText());
            stat.setString(3, cbjabatan.getSelectedItem().toString());
            stat.setString(4, gajipokok.getText());
            stat.setString(5, txtnb.getText());
            stat.setString(6, txtbns.getText());
            stat.setString(7, txtbonus.getText());
            stat.setString(8, hbpjs.getText());
            stat.setString(9, hpajak.getText());
            stat.setString(10, gakor.getText());
            stat.setString(11, txttotal.getText());
            stat.setString(12, idtrx.getText());
            

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            autotrx();
            txtid.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null,"data gagal disimpan"+e);
        }
        datatable();
    }//GEN-LAST:event_bsimpan2ActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "hapus","konfirmasi dialog",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            String sql = "delete from transaksi where id ='"+txtid.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil di hapus");
                kosong();
                txtid.requestFocus();
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal di hapus"+e);
            }
            datatable();
            autotrx();
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void txtbnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbnsActionPerformed
        // TODO add your handling code here:
        double ab = Double.parseDouble(txtbns.getText());
        double bns;
        if(ab >=25){
            bns = 200000;
        }else{
            bns = 0;
        }
        
        txtbonus.setText(String.valueOf(bns));
    }//GEN-LAST:event_txtbnsActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new datapegawai().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new dataabsen().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new datagaji().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new datarekening().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new datatunjangan().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new transaksigaji().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        
         try {
             String path="src/tampilan/transaksi.jasper";
             HashMap parameter = new HashMap();
             parameter.put("id_transaksi",txtcetak.getText());
             JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
             JasperViewer.viewReport(print,false);
         } catch (Exception ex) {
             JOptionPane.showMessageDialog(rootPane, "Dokumen Tidak Ada" +ex);
         }

    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksigaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksigaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksigaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksigaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksigaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bhitung;
    private javax.swing.JTextField bpjs;
    private javax.swing.JButton bsimpan2;
    private javax.swing.JComboBox<String> cbjabatan;
    private javax.swing.JButton edit;
    private javax.swing.JTextField gajipokok;
    private javax.swing.JTextField gakor;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField hbpjs;
    private javax.swing.JTextField hpajak;
    private javax.swing.JTextField idtrx;
    private javax.swing.JPanel isi1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pajak;
    private javax.swing.JTable tblpegawai;
    private javax.swing.JComboBox<String> txtbln;
    private javax.swing.JTextField txtbns;
    private javax.swing.JTextField txtbonus;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtcetak;
    private javax.swing.JTextField txtid;
    private javax.swing.JComboBox<String> txtket;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnb;
    private javax.swing.JTextField txtnm1;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttotal1;
    // End of variables declaration//GEN-END:variables
}
